SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE IF NOT EXISTS `architecture` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `tech_stack_id` bigint NOT NULL COMMENT 'FK: tech_stack.id',
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '아키텍처 이름 (예: hexagonal-multimodule)',
  `pattern_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'HEXAGONAL, LAYERED, CLEAN, etc.',
  `pattern_description` text COLLATE utf8mb4_unicode_ci COMMENT '패턴 설명',
  `pattern_principles` json DEFAULT NULL COMMENT '["DIP", "SRP", "OCP", "ISP"]',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_architecture_name` (`tech_stack_id`,`name`),
  KEY `idx_architecture_pattern` (`pattern_type`),
  CONSTRAINT `fk_architecture_tech_stack` FOREIGN KEY (`tech_stack_id`) REFERENCES `tech_stack` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='아키텍처 패턴 정의';
CREATE TABLE IF NOT EXISTS `archunit_test` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `convention_id` bigint NOT NULL COMMENT '컨벤션 ID',
  `structure_id` bigint DEFAULT NULL COMMENT '적용 대상 구조 (NULL이면 전체)',
  `code` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '테스트 코드 (예: ARCH-001)',
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '테스트 이름',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT '테스트 설명',
  `test_class_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '테스트 클래스명 (예: RestApiArchTest)',
  `test_method_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '테스트 메서드명',
  `test_code` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '실제 ArchUnit 테스트 코드',
  `severity` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'BLOCKER' COMMENT 'BLOCKER, CRITICAL, MAJOR, MINOR',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_archunit_test_code` (`convention_id`,`code`),
  KEY `fk_archunit_test_structure` (`structure_id`),
  KEY `idx_test_class` (`test_class_name`),
  CONSTRAINT `fk_archunit_test_convention` FOREIGN KEY (`convention_id`) REFERENCES `convention` (`id`),
  CONSTRAINT `fk_archunit_test_structure` FOREIGN KEY (`structure_id`) REFERENCES `package_structure` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=159 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ArchUnit 아키텍처 테스트 코드';
CREATE TABLE IF NOT EXISTS `checklist_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `rule_id` bigint NOT NULL COMMENT 'FK: coding_rule.id',
  `sequence_order` int NOT NULL COMMENT '체크 순서',
  `check_description` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '체크 항목 설명',
  `check_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'AUTOMATED, MANUAL, SEMI_AUTO',
  `automation_tool` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'ARCHUNIT, CHECKSTYLE, PMD, etc.',
  `automation_rule_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '자동화 도구의 규칙 ID',
  `is_critical` tinyint(1) NOT NULL DEFAULT '0' COMMENT '필수 항목 여부',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `source` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'MANUAL' COMMENT '출처 (MANUAL, AGENT_FEEDBACK)',
  `feedback_id` bigint DEFAULT NULL COMMENT 'review_feedback ID (에이전트 피드백에서 승격된 경우)',
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_checklist_order` (`rule_id`,`sequence_order`),
  KEY `idx_checklist_type` (`check_type`),
  KEY `fk_checklist_item_feedback` (`feedback_id`),
  CONSTRAINT `fk_checklist_item_feedback` FOREIGN KEY (`feedback_id`) REFERENCES `review_feedback` (`id`),
  CONSTRAINT `fk_checklist_rule` FOREIGN KEY (`rule_id`) REFERENCES `coding_rule` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='코딩 규칙 체크리스트';
CREATE TABLE IF NOT EXISTS `class_template` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `convention_id` bigint NOT NULL COMMENT 'FK: convention.id',
  `class_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'AGGREGATE, VALUE_OBJECT, SERVICE, REPOSITORY, etc.',
  `template_code` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '템플릿 코드 ({ClassName} 등 플레이스홀더 사용)',
  `naming_pattern` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '클래스명 패턴 (정규식)',
  `required_annotations` json DEFAULT NULL COMMENT '필수 어노테이션 목록',
  `forbidden_annotations` json DEFAULT NULL COMMENT '금지 어노테이션 목록',
  `required_interfaces` json DEFAULT NULL COMMENT '필수 인터페이스 목록',
  `forbidden_inheritance` json DEFAULT NULL COMMENT '금지 상속 목록',
  `required_methods` json DEFAULT NULL COMMENT '필수 메서드 목록',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT '템플릿 설명',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `structure_id` bigint DEFAULT NULL COMMENT 'FK: package_structure.id - 템플릿이 적용되는 패키지 구조',
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_class_template_convention_type_naming` (`convention_id`,`class_type`,`naming_pattern`),
  KEY `idx_class_template_type` (`class_type`),
  KEY `idx_class_template_structure` (`structure_id`),
  CONSTRAINT `fk_class_template_structure` FOREIGN KEY (`structure_id`) REFERENCES `package_structure` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=185 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='클래스 템플릿 정의';
CREATE TABLE IF NOT EXISTS `coding_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `convention_id` bigint NOT NULL COMMENT 'FK: convention.id',
  `code` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '규칙 코드 (예: DOM-001, APP-001)',
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '규칙 이름',
  `severity` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BLOCKER, CRITICAL, MAJOR, MINOR, INFO',
  `category` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ANNOTATION, BEHAVIOR, STRUCTURE, DEPENDENCY, etc.',
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '규칙 상세 설명',
  `rationale` text COLLATE utf8mb4_unicode_ci COMMENT '규칙 근거/이유',
  `auto_fixable` tinyint(1) NOT NULL DEFAULT '0' COMMENT '자동 수정 가능 여부',
  `is_zero_tolerance` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Zero-Tolerance 규칙 여부',
  `applies_to` json DEFAULT NULL COMMENT '적용 대상 ["CLASS", "METHOD", "FIELD"]',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `structure_id` bigint DEFAULT NULL COMMENT 'FK: package_structure.id - 규칙이 적용되는 패키지 구조',
  `sdk_artifact` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'SDK artifact (NULL이면 SDK 무관)',
  `sdk_min_version` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'SDK 최소 버전',
  `sdk_max_version` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'SDK 최대 버전 (NULL이면 최신까지)',
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_coding_rule_code` (`convention_id`,`code`),
  KEY `idx_coding_rule_severity` (`severity`),
  KEY `idx_coding_rule_zt` (`is_zero_tolerance`),
  KEY `idx_coding_rule_structure` (`structure_id`),
  CONSTRAINT `fk_coding_rule_convention` FOREIGN KEY (`convention_id`) REFERENCES `convention` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_coding_rule_structure` FOREIGN KEY (`structure_id`) REFERENCES `package_structure` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=425 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='코딩 규칙 정의';
CREATE TABLE IF NOT EXISTS `convention` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `architecture_id` bigint NOT NULL COMMENT 'FK: architecture.id',
  `layer` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'DOMAIN, APPLICATION, PERSISTENCE, REST_API, TESTING',
  `version` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '1.0.0' COMMENT '컨벤션 버전',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT '컨벤션 설명',
  `is_active` tinyint(1) NOT NULL DEFAULT '1' COMMENT '활성화 여부',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_convention_layer` (`architecture_id`,`layer`,`version`),
  KEY `idx_convention_active` (`is_active`),
  CONSTRAINT `fk_convention_architecture` FOREIGN KEY (`architecture_id`) REFERENCES `architecture` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='레이어별 코딩 컨벤션 정의';
CREATE TABLE IF NOT EXISTS `layer_dependency_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `architecture_id` bigint NOT NULL COMMENT 'FK: architecture.id',
  `from_layer` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '의존하는 레이어 (ADAPTER_IN, APPLICATION, etc.)',
  `to_layer` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '의존되는 레이어',
  `dependency_type` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ALLOWED, FORBIDDEN, CONDITIONAL',
  `condition_description` text COLLATE utf8mb4_unicode_ci COMMENT 'CONDITIONAL인 경우 조건 설명',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_layer_dependency` (`architecture_id`,`from_layer`,`to_layer`),
  KEY `idx_layer_from` (`from_layer`),
  KEY `idx_layer_to` (`to_layer`),
  CONSTRAINT `fk_layer_dep_architecture` FOREIGN KEY (`architecture_id`) REFERENCES `architecture` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='레이어 간 의존성 규칙 정의';
CREATE TABLE IF NOT EXISTS `module` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `architecture_id` bigint NOT NULL COMMENT 'FK: architecture.id',
  `parent_module_id` bigint DEFAULT NULL COMMENT 'FK: module.id (부모 모듈)',
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '모듈 이름 (예: domain, application)',
  `module_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'DOMAIN, APPLICATION, ADAPTER_IN, ADAPTER_OUT, COMMON',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT '모듈 설명',
  `gradle_path` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Gradle 모듈 경로 (예: :domain, :adapter-in:rest-api)',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_module_name` (`architecture_id`,`name`),
  KEY `idx_module_type` (`module_type`),
  KEY `idx_module_parent` (`parent_module_id`),
  CONSTRAINT `fk_module_architecture` FOREIGN KEY (`architecture_id`) REFERENCES `architecture` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_module_parent` FOREIGN KEY (`parent_module_id`) REFERENCES `module` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Gradle 모듈 정의';
CREATE TABLE IF NOT EXISTS `package_purpose` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `module_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'DOMAIN, APPLICATION, ADAPTER_IN, ADAPTER_OUT',
  `code` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'AGGREGATE, VALUE_OBJECT, PORT_IN 등',
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '표시명 (애그리거트, 값 객체 등)',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT '설명',
  `default_allowed_class_types` json DEFAULT NULL COMMENT '기본 허용 클래스 타입',
  `default_naming_pattern` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '기본 네이밍 패턴 (정규식)',
  `default_naming_suffix` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '기본 접미사',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_package_purpose` (`module_type`,`code`)
) ENGINE=InnoDB AUTO_INCREMENT=86 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='패키지 목적 정의';
CREATE TABLE IF NOT EXISTS `package_structure` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `module_id` bigint NOT NULL COMMENT 'FK: module.id',
  `purpose_id` bigint DEFAULT NULL COMMENT 'FK: package_purpose.id',
  `path_pattern` varchar(300) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '패키지 경로 패턴 (예: {base}.domain.{bc}.aggregate)',
  `allowed_class_types` json NOT NULL COMMENT '["AGGREGATE_ROOT", "ENTITY", "VALUE_OBJECT"]',
  `naming_pattern` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '클래스 네이밍 패턴 (정규식)',
  `naming_suffix` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '클래스 접미사 (예: Service, Repository)',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT '패키지 설명',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_package_path` (`module_id`,`path_pattern`),
  KEY `fk_package_purpose` (`purpose_id`),
  CONSTRAINT `fk_package_module` FOREIGN KEY (`module_id`) REFERENCES `module` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_package_purpose` FOREIGN KEY (`purpose_id`) REFERENCES `package_purpose` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=85 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='모듈 내 패키지 구조 정의';
CREATE TABLE IF NOT EXISTS `resource_template` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `module_id` bigint NOT NULL COMMENT '모듈 ID',
  `category` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'CONFIG, I18N, STATIC, BUILD',
  `file_path` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '파일 경로 (예: application-{profile}.yml)',
  `file_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'YAML, PROPERTIES, JSON, GRADLE',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT '설명',
  `template_content` text COLLATE utf8mb4_unicode_ci COMMENT '템플릿 내용',
  `required` tinyint(1) DEFAULT '1' COMMENT '필수 여부',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_resource_template` (`module_id`,`file_path`),
  KEY `idx_category` (`category`),
  CONSTRAINT `fk_resource_template_module` FOREIGN KEY (`module_id`) REFERENCES `module` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='리소스 파일 템플릿 (yml, properties, gradle 등)';
CREATE TABLE IF NOT EXISTS `review_feedback` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `session_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '작업 세션 ID',
  `agent_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'WORKER, REVIEWER',
  `rule_id` bigint DEFAULT NULL COMMENT 'coding_rule ID',
  `structure_id` bigint DEFAULT NULL COMMENT 'package_structure ID',
  `sdk_rule_id` bigint DEFAULT NULL COMMENT 'sdk_usage_rule ID',
  `review_result` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'PASS, FAIL, PARTIAL',
  `score` decimal(3,2) DEFAULT NULL COMMENT '점수 (0.00 ~ 1.00)',
  `original_code` text COLLATE utf8mb4_unicode_ci COMMENT 'Worker가 생성한 원본 코드',
  `corrected_code` text COLLATE utf8mb4_unicode_ci COMMENT 'Reviewer가 수정한 코드',
  `feedback_note` text COLLATE utf8mb4_unicode_ci COMMENT '리뷰 코멘트',
  `promoted_to` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'GOOD_EXAMPLE, BAD_EXAMPLE, CHECKLIST_ITEM',
  `promoted_id` bigint DEFAULT NULL COMMENT '승격된 레코드 ID',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_review_feedback_rule` (`rule_id`),
  KEY `fk_review_feedback_structure` (`structure_id`),
  KEY `fk_review_feedback_sdk_rule` (`sdk_rule_id`),
  KEY `idx_session` (`session_id`),
  KEY `idx_review_result` (`review_result`),
  KEY `idx_promoted` (`promoted_to`),
  CONSTRAINT `fk_review_feedback_rule` FOREIGN KEY (`rule_id`) REFERENCES `coding_rule` (`id`),
  CONSTRAINT `fk_review_feedback_sdk_rule` FOREIGN KEY (`sdk_rule_id`) REFERENCES `sdk_usage_rule` (`id`),
  CONSTRAINT `fk_review_feedback_structure` FOREIGN KEY (`structure_id`) REFERENCES `package_structure` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='에이전트 리뷰 피드백 (학습 데이터)';
CREATE TABLE IF NOT EXISTS `rule_example` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `rule_id` bigint NOT NULL COMMENT 'FK: coding_rule.id',
  `example_type` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'GOOD, BAD',
  `code` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '예시 코드',
  `language` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'JAVA' COMMENT 'JAVA, KOTLIN, SQL, etc.',
  `explanation` text COLLATE utf8mb4_unicode_ci COMMENT '예시 설명',
  `highlight_lines` json DEFAULT NULL COMMENT '강조할 라인 번호 [1, 3, 5]',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `source` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'MANUAL' COMMENT '출처 (MANUAL, AGENT_FEEDBACK)',
  `feedback_id` bigint DEFAULT NULL COMMENT 'review_feedback ID (에이전트 피드백에서 승격된 경우)',
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_rule_example_type` (`example_type`),
  KEY `fk_rule_example_rule` (`rule_id`),
  KEY `fk_rule_example_feedback` (`feedback_id`),
  CONSTRAINT `fk_rule_example_feedback` FOREIGN KEY (`feedback_id`) REFERENCES `review_feedback` (`id`),
  CONSTRAINT `fk_rule_example_rule` FOREIGN KEY (`rule_id`) REFERENCES `coding_rule` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=124 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='코딩 규칙 Good/Bad 예시';
CREATE TABLE IF NOT EXISTS `sdk_setup_guide` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `sdk_artifact` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'SDK artifact',
  `sdk_version_id` bigint DEFAULT NULL COMMENT 'SDK 버전 (NULL이면 전체 버전 공통)',
  `guide_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'DEPENDENCY, INITIALIZATION, CONFIGURATION, MIGRATION',
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '가이드 이름',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT '가이드 설명',
  `code_example` text COLLATE utf8mb4_unicode_ci COMMENT '코드 예시',
  `file_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '파일 타입 (GRADLE, YAML, JAVA, KOTLIN)',
  `priority` int DEFAULT '0' COMMENT '표시 순서',
  `deprecated` tinyint(1) DEFAULT '0' COMMENT '비권장 여부',
  `superseded_by` bigint DEFAULT NULL COMMENT '대체된 가이드 ID',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_sdk_setup_guide_version` (`sdk_version_id`),
  KEY `fk_sdk_setup_guide_superseded` (`superseded_by`),
  KEY `idx_sdk_artifact` (`sdk_artifact`),
  KEY `idx_guide_type` (`guide_type`),
  CONSTRAINT `fk_sdk_setup_guide_superseded` FOREIGN KEY (`superseded_by`) REFERENCES `sdk_setup_guide` (`id`),
  CONSTRAINT `fk_sdk_setup_guide_version` FOREIGN KEY (`sdk_version_id`) REFERENCES `sdk_version` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='SDK 셋업 가이드 (초기화, 설정, 마이그레이션)';
CREATE TABLE IF NOT EXISTS `sdk_usage_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `convention_id` bigint NOT NULL COMMENT '컨벤션 ID',
  `code` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '규칙 코드 (예: SDK-001)',
  `target_scope` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '적용 범위 (예: module:rest-api, package:**.controller.**)',
  `sdk_artifact` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'SDK artifact',
  `min_version` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '최소 버전',
  `max_version` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '최대 버전',
  `usage_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'REQUIRED, FORBIDDEN, RECOMMENDED',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT '규칙 설명',
  `rationale` text COLLATE utf8mb4_unicode_ci COMMENT '규칙 근거',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sdk_usage_rule_code` (`convention_id`,`code`),
  KEY `idx_target_scope` (`target_scope`),
  KEY `idx_sdk_artifact` (`sdk_artifact`),
  CONSTRAINT `fk_sdk_usage_rule_convention` FOREIGN KEY (`convention_id`) REFERENCES `convention` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='SDK 사용 규칙 (어디서 뭘 써라/쓰지마라)';
CREATE TABLE IF NOT EXISTS `sdk_version` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `sdk_artifact` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'SDK artifact (예: com.ryuqq:observability-sdk)',
  `version` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '버전 (예: 2.0.0)',
  `release_date` date DEFAULT NULL COMMENT '릴리스 날짜',
  `changelog` text COLLATE utf8mb4_unicode_ci COMMENT '변경 내역',
  `is_latest` tinyint(1) DEFAULT '0' COMMENT '최신 버전 여부',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sdk_version` (`sdk_artifact`,`version`),
  KEY `idx_sdk_artifact` (`sdk_artifact`),
  KEY `idx_is_latest` (`is_latest`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='SDK 버전 관리';
CREATE TABLE IF NOT EXISTS `tech_stack` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '기술 스택 이름 (예: java21-spring35-backend)',
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE, DEPRECATED, ARCHIVED',
  `language_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'JAVA, KOTLIN, TYPESCRIPT, etc.',
  `language_version` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '21, 17, 5.0, etc.',
  `language_features` json DEFAULT NULL COMMENT '["VIRTUAL_THREAD", "RECORD", "PATTERN_MATCHING"]',
  `framework_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'SPRING_BOOT, SPRING_CLOUD, KTOR, etc.',
  `framework_version` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '3.5.0, 2.7.x, etc.',
  `framework_modules` json DEFAULT NULL COMMENT '["WEB", "JPA", "SECURITY", "ACTUATOR"]',
  `platform_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BACKEND, FRONTEND, FULLSTACK, SDK',
  `runtime_environment` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'JVM, GraalVM, V8, etc.',
  `build_tool_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'GRADLE, MAVEN, NPM, etc.',
  `build_config_file` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'build.gradle, pom.xml, package.json',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tech_stack_name` (`name`),
  KEY `idx_tech_stack_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='기술 스택 정의 (언어, 프레임워크, 빌드 도구)';
CREATE TABLE IF NOT EXISTS `zero_tolerance_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `convention_id` bigint NOT NULL COMMENT 'FK: convention.id',
  `rule_id` bigint NOT NULL COMMENT 'FK: coding_rule.id',
  `type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'LOMBOK_IN_DOMAIN, SETTER_USAGE, etc.',
  `detection_pattern` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '탐지 패턴 (정규식)',
  `detection_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'REGEX, AST, ARCHUNIT',
  `auto_reject_pr` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'PR 자동 거부 여부',
  `error_message` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '에러 메시지',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_zt_rule` (`convention_id`,`rule_id`),
  KEY `idx_zt_type` (`type`),
  KEY `fk_zt_rule` (`rule_id`),
  CONSTRAINT `fk_zt_convention` FOREIGN KEY (`convention_id`) REFERENCES `convention` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_zt_rule` FOREIGN KEY (`rule_id`) REFERENCES `coding_rule` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Zero-Tolerance 규칙 상세 정의';
SET FOREIGN_KEY_CHECKS = 1;
