# ============================================================
# Persistence Layer 운영 환경 설정
# ============================================================
# 활성화: spring.profiles.active=prod
# ⚠️ 모든 민감 정보는 환경 변수로 관리
# ============================================================

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?useSSL=true&requireSSL=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      # ─────────────────────────────────────────────────────────
      # Pool Size (운영: CPU 기반)
      # 공식: connections = (core_count * 2) + effective_spindle_count
      # ─────────────────────────────────────────────────────────
      maximum-pool-size: 20
      minimum-idle: 10

      # ─────────────────────────────────────────────────────────
      # Timeout 설정
      # ─────────────────────────────────────────────────────────
      connection-timeout: 30000       # 커넥션 획득 대기 (30초)
      validation-timeout: 5000        # 커넥션 유효성 검사 (5초)
      idle-timeout: 600000            # 유휴 커넥션 유지 (10분)
      max-lifetime: 1800000           # 커넥션 최대 수명 (30분)
      keepalive-time: 30000           # keepalive 쿼리 주기 (30초, MySQL wait_timeout 방지)

      # ─────────────────────────────────────────────────────────
      # Leak Detection (운영: 강화)
      # 30초 이상 반환되지 않은 커넥션 감지
      # ─────────────────────────────────────────────────────────
      leak-detection-threshold: 30000

      # ─────────────────────────────────────────────────────────
      # Pool 설정
      # ─────────────────────────────────────────────────────────
      pool-name: HikariPool-Prod
      auto-commit: false              # 명시적 트랜잭션 관리
      register-mbeans: true           # JMX 모니터링 활성화

      # ─────────────────────────────────────────────────────────
      # Connection Health Check
      # ─────────────────────────────────────────────────────────
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1

      # ─────────────────────────────────────────────────────────
      # MySQL 최적화 (운영)
      # ─────────────────────────────────────────────────────────
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  jpa:
    hibernate:
      # Flyway가 스키마 관리, Hibernate는 검증하지 않음
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

  flyway:
    # ⚠️ 운영에서 clean 절대 금지
    clean-disabled: true
    # Checksum 검증 비활성화 (공유 DB에서 다른 프로젝트 마이그레이션 충돌 방지)
    validate-on-migrate: false

logging:
  level:
    com.ryuqq: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
