source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-theme-cayman"
gem "jekyll-relative-links"
gem "jekyll-optional-front-matter"
gem "jekyll-readme-index"
gem "jekyll-titles-from-headings"
gem "webrick"
